spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    database: postgresql
logging:
  level:
    root: INFO
    com.kth.blog: DEBUG
    org.springframework.web: INFO
    org.hibernate: ERROR
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.boot.context.config: DEBUG
    org.springframework.core.env: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
