spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
#    username: sa
#    password: sa
#  h2:
#    console: # H2 DB를 웹에서 관리할 수 있는 기능
#      enabled: false           # H2 Console 사용 여부
#      path: /h2-console       # H2 Console 접속 주소

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    database: postgresql

  elasticsearch:
    uris: http://elasticsearch:9200

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: blog-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: java.lang.Object

logging:
  level:
    root: INFO
    com.kth.blog: DEBUG
    org.springframework.web: INFO
    org.hibernate: ERROR
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
  file:
    name: /app/logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoint:
    health:
      show-details: always
      enabled: true
      web:
        exposure:
          include: health

# Elasticsearch 클러스터 설정
elasticsearch:
  cluster:
    name: blog-cluster
  index:
    posts:
      name: posts
      shards: 1
      replicas: 1